/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppHome {}
  interface PedalBoard {}
  interface PedalBoost {}
  interface PedalOverdrive {}
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLPedalBoardElement extends Components.PedalBoard, HTMLStencilElement {}
  var HTMLPedalBoardElement: {
    prototype: HTMLPedalBoardElement;
    new (): HTMLPedalBoardElement;
  };

  interface HTMLPedalBoostElement extends Components.PedalBoost, HTMLStencilElement {}
  var HTMLPedalBoostElement: {
    prototype: HTMLPedalBoostElement;
    new (): HTMLPedalBoostElement;
  };

  interface HTMLPedalOverdriveElement extends Components.PedalOverdrive, HTMLStencilElement {}
  var HTMLPedalOverdriveElement: {
    prototype: HTMLPedalOverdriveElement;
    new (): HTMLPedalOverdriveElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'pedal-board': HTMLPedalBoardElement;
    'pedal-boost': HTMLPedalBoostElement;
    'pedal-overdrive': HTMLPedalOverdriveElement;
  }
}

declare namespace LocalJSX {
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {}
  interface PedalBoard extends JSXBase.HTMLAttributes<HTMLPedalBoardElement> {}
  interface PedalBoost extends JSXBase.HTMLAttributes<HTMLPedalBoostElement> {}
  interface PedalOverdrive extends JSXBase.HTMLAttributes<HTMLPedalOverdriveElement> {}

  interface IntrinsicElements {
    'app-home': AppHome;
    'pedal-board': PedalBoard;
    'pedal-boost': PedalBoost;
    'pedal-overdrive': PedalOverdrive;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


